bot_token = "<Token>"
chrome_driver_path = "<Path>"
node_settings = dict(
    host="127.0.0.1",
    port=80,
    rest_uri="http://127.0.0.1:80",
    password="<Password>",
    identifier="<ID>",
    region="europe"
)
mongo_db_url = "<mongodb>"
x_naver_client_id = "<ID>"
x_naver_client_secret = "<Secret>"
t_b = ["Int(TriviaBotID)"]
t_c = ["Int(TriviaBotChannel)"]
t_g_a = "Int(TriviaGuildAnswerChannel)"
t_c_a = "Int(TriviaAnswerChannel)"
t_q_h = "Str(TriviaQuestionHeader)"
t_a_h = ["Str(TriviaAnswerHeader)"]
